### ISSUE TITLE
next-auth: OAUTH_PARSE_PROFILE_ERROR with azure-ad

### ISSUE THREAD

**Issue by zqtay** [zqtay/tech-notes#1]
### Description
`next-auth` occasionally fails during user sign in with `azure-ad` as auth provider. No error is shown in the front end and user is redirect back to the sign in page.  

### Affected library
next-auth@4.24.5
next@13.2.3

### Behavior
```
[next-auth][error][OAUTH_PARSE_PROFILE_ERROR] 
https://next-auth.js.org/errors#oauth_parse_profile_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Object.profile (<project-path>\\node_modules\\next-auth\\providers\\azure-ad.js:27:24)\n' +
      '    at async getProfile (<project-path>\\node_modules\\next-auth\\core\\lib\\oauth\\callback.js:162:21)\n' +
      '    at async oAuthCallback (<project-path>\\node_modules\\next-auth\\core\\lib\\oauth\\callback.js:136:27)\n' +
      '    at async Object.callback (<project-path>\\node_modules\\next-auth\\core\\routes\\callback.js:52:11)\n' +
      '    at async AuthHandler (<project-path>\\node_modules\\next-auth\\core\\index.js:208:28)\n' + 
      '    at async NextAuthApiHandler (<project-path>\\node_modules\\next-auth\\next\\index.js:22:19)\n' +
      '    at async NextAuth._args$ (<project-path>\\node_modules\\next-auth\\next\\index.js:108:14)\n' +
      '    at async Object.apiResolver (<project-path>\\node_modules\\next\\dist\\server\\api-utils\\node.js:372:9)\n' +
      '    at async DevServer.runApi (<project-path>\\node_modules\\next\\dist\\server\\next-server.js:513:9)\n' +
      '    at async Object.fn (<project-path>\\node_modules\\next\\dist\\server\\next-server.js:815:35)\n' +
      '    at async Router.execute (<project-path>\\node_modules\\next\\dist\\server\\router.js:243:32)\n' +
      '    at async DevServer.runImpl (<project-path>\\node_modules\\next\\dist\\server\\base-server.js:432:29)\n' +
      '    at async DevServer.run (<project-path>\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js:814:20)\n' +
      '    at async DevServer.handleRequestImpl (<project-path>\\node_modules\\next\\dist\\server\\base-server.js:375:20)\n' +
      '    at async <project-path>\\node_modules\\next\\dist\\server\\base-server.js:157:99',
    name: 'TypeError'
  },
  OAuthProfile: {
    aud: '...',
    iss: 'https://login.microsoftonline.com/.../v2.0',
    iat: 1724898609,
    nbf: 1724898609,
    exp: 1724902509,
    email: '<user-email>',
    name: '<user-name>',
    oid: '...',
    preferred_username: '<user-email>',
    rh: '...
    sub: '...',
    tid: '...',
    uti: '...',
    ver: '2.0'
  },
  message: 'fetch failed'
}
```

### Code
```typescript
// \src\pages\api\auth\[...nextauth].ts
export const authOptions: NextAuthOptions = {
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID ?? "",
      clientSecret: process.env.AZURE_AD_CLIENT_SECRET ?? "",
      tenantId: process.env.AZURE_AD_TENANT_ID,
      allowDangerousEmailAccountLinking: true,
    }),
  ],
  ...
};
```

**Comment by zqtay** [comment]
### Investigation
From the server error message, it seems to fail while fetching profile image.
```javascript
// \node_modules\next-auth\providers\azure-ad.js
async profile(profile, tokens) {
  var _image;
  // Fetch error thrown in next line
  const response = await fetch(`https://graph.microsoft.com/v1.0/me/photos/${profilePhotoSize}x${profilePhotoSize}/$value`, {
    headers: {
      Authorization: `Bearer ${tokens.access_token}`
    }
  });
  let image;

  if (response.ok && typeof Buffer !== "undefined") {
    try {
      const pictureBuffer = await response.arrayBuffer();
      const pictureBase64 = Buffer.from(pictureBuffer).toString("base64");
      image = `data:image/jpeg;base64, ${pictureBase64}`;
    } catch (_unused) {}
  }

  return {
    id: profile.sub,
    name: profile.name,
    email: profile.email,
    image: (_image = image) !== null && _image !== void 0 ? _image : null
  };
},
```

**Comment by zqtay** [comment]
### Workaround
Skip fetching profile image if it is not used.
```typescript
// \src\pages\api\auth\[...nextauth].ts
export const authOptions: NextAuthOptions = {
  providers: [
    AzureADProvider({
      clientId: process.env.AZURE_AD_CLIENT_ID ?? "",
      clientSecret: process.env.AZURE_AD_CLIENT_SECRET ?? "",
      tenantId: process.env.AZURE_AD_TENANT_ID,
      allowDangerousEmailAccountLinking: true,
      // Add the following lines to override profile function
      async profile(profile, tokens) {
        return {
          id: profile.sub,
          name: profile.name,
          email: profile.email,
          image: null,
        } as any;
      },
    }),
  ],
  ...
};
```

**Comment by zqtay** [comment]
### Additional info
Profile image request with Postman
![image](https://github.com/user-attachments/assets/a2d03eb3-591c-43d2-b44b-d809918e6c53)
